MVCStore/Controllers/PagesController.cs
using MVCStore.Models.Data;
using MVCStore.Models.ViewModels.Pages;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCStore.Controllers
{
    public class PagesController : Controller
    {
        // GET: Index/{page}
        [HttpGet]
         public ActionResult Index(string page = "")
        {
            // get/set  slug
            if (string.IsNullOrEmpty(page))
                page = "home";
            //declare models and class dto
            PageVM model;
            PagesDTO dto;

            //check page availiblity  
            using (Db db = new Db())
            {
                if (!db.Pages.Any(x => x.Slug == (page)))
                    return RedirectToAction("Index", new { page = "" });
            }
            //get dto of page
            using (Db db = new Db())
            {
                dto = db.Pages.Where(x => x.Slug == page).FirstOrDefault();
            }
            //set title of page
            ViewBag.PageTitle = dto.Title;
            //check sidebar
            ViewBag.SideBar = dto.HasSidebar;
            
            //fill model with data
            model = new PageVM(dto);
            //return view
            return View(model);
        }



        public ActionResult PagesMenuPartial()
        {
            //init  list of page
            List<PageVM> pageVMList;
            //get all pages except home
            using(Db db = new Db())
            {
                pageVMList = db.Pages.ToArray().OrderBy(x => x.Sorting).Where(x => x.Slug != "home").Select(x => new PageVM(x)).ToList();
            }
            //return list in partial  view

            return PartialView("_PagesMenuPartial", pageVMList);
        }

        public ActionResult SidebarPartial()
        {
            //declare model
            SidebarVM model;

            //init model
            using (Db db = new Db())
            {
                SidebarDTO dto = db.Sidebars.Find(1);
                model = new SidebarVM(dto);
            }

            //return model in partial view
            return PartialView("_SidebarPartial",model);
        }
    }
}

MVCStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVCSHOP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="/">ShoppohS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                @Html.Action("PagesMenuPartial", "Pages")


                @if (Request.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "navbar-text", style = "text_decoration:none" })</li>
                }
                else
                {
                    if (ViewBag.Title == "Login")
                    {
                        <li class="navbar-text">@Html.ActionLink("Login", "Login", "Account", null, new { @class = "active", style = "text_decoration:none" })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account", null, new { @class = "navbar-text ", style = "text_decoration:none" })</li>
                    }
                }
                @if (Request.IsAuthenticated && User.IsInRole("User"))
                {
                    if (ViewBag.Title == "User Profile")
                    {

                        <li class="active">@Html.Action("UserNavPartial", "Account", new { area = "" })</li>
                    }
                    else
                    {
                        <li>@Html.Action("UserNavPartial", "Account", new { area = "" })</li>

                    }
                }
            </ul>
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <span class="navbar-text">
                    @Html.ActionLink("AdminArea", "Index", "Dashboard", new { area = "Admin" }, null)
                </span>
            }
            else
            {
                if (ViewBag.Title != "Cart Details")
                {
                    <span class="navbar-text">
                        @Html.Action("CartPartial", "Cart")
                    </span>

                }
            }
        </div>
    </nav>
    <div class="container body-content" style="margin-top:30px">
        <div class="row">
            <!--Menu-->

            <div class="col-sm-12 col-md-3 list-group">
                @Html.Action("CategoryMenuPartial", "Shop")
            </div>
            <!--Sidebar-->
            @if (ViewBag.Sidebar != null && ViewBag.Sidebar)
            {
                <div class="col">
                    @RenderBody()
                </div>
                <div class="col-sm-12 col-md-3">
                    @Html.Action("SidebarPartial", "Pages")
                </div>
            }
            else
            {
                <div class="col">
                    @RenderBody()
                </div>
            }
        </div>
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - MVCSHOP</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>